name: Keyboard Warrior
description: Breaking software is just finding unintended features, right?
meta_description: "Keyboard Warrior, Breaking software is just finding unintended features, right?"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: "https:/RealKeyboardWarrior.github.io"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Florian Mathieu"

# Disqus config
disqus-shortname: ""
